### ISSUE TITLE
ejabberd broken after upgrade to 16.06

### ISSUE THREAD

**Issue by tbeitter** [jabber-at/ejabberd#11]
> What version of ejabberd are you using?

upgraded to 16.06

> What operating system (version) are you using?

debian 7.11 wheezy
erlang-p1-tls | 1.0.4-0.1~afa70 | https://apt.jabber.at/ wheezy/ejabberd amd64 Packages

> How did you install ejabberd (source, package, distribution)?

jabber.at-Repository

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

after the upgrade from 16.04 to 16.06 ejabberd no longer starts. crash log tells:

```
2016-06-30 21:34:21 =ERROR REPORT====
failed to load TLS driver: undefined symbol: erl_exit
2016-06-30 21:34:21 =CRASH REPORT====
  crasher:
    initial call: fast_tls:init/1
    pid: <0.130.0>
    registered_name: []
    exception exit: {{open_error,-10},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,344}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [fast_tls_sup,<0.128.0>]
    messages: []
    links: [<0.129.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 26622
  neighbours:
2016-06-30 21:34:21 =SUPERVISOR REPORT====
     Supervisor: {local,fast_tls_sup}
     Context:    start_error
     Reason:     {open_error,-10}
     Offender:   [{pid,undefined},{id,fast_tls},{mfargs,{fast_tls,start_link,[]}},{restart_type,permanent},{shutdown,brutal_kill},{child_type,worker}]

2016-06-30 21:34:21 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.127.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,fast_tls,{open_error,-10}}},{fast_tls_app,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.126.0>]
    messages: [{'EXIT',<0.128.0>,normal}]
    links: [<0.126.0>,<0.31.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 122
  neighbours:
```

**Comment by mathiasertl** [comment]
I cannot reproduce this on my local testserver, even in wheezy. Can you post the output of `dpkg -l erlang-base ejabberd erlang-p1-tls`?

The diff between erlang-p1-tls 1.0.3 (used in ejabberd 16.04) and 1.0.4 does show a change that might be related to this problem:

```difff
--- a/c_src/fast_tls_drv.c
+++ b/c_src/fast_tls_drv.c
@@ -55,14 +55,7 @@ typedef unsigned __int32 uint32_t;
 
 /* Wrappers around driver_alloc() that check  */
 /* for OOM.                                   */
-
-#ifdef HAS_ERTS_EXIT
-void erts_exit(int n, char* v, ...);
-#define erl_exit erts_exit
-#else
-void erl_exit(int n, char* v, ...);
-#endif
-
+void erl_exit(int n, char* v, ...) { abort(); }
 void *ftls_alloc(ErlDrvSizeT size);
 void *ftls_realloc(void *ptr, ErlDrvSizeT size);
 ErlDrvBinary *ftls_alloc_binary(ErlDrvSizeT size);
```

**Comment by tbeitter** [comment]
```
iF  ejabberd                                        1:16.06-1~afa70              amd64
ii  erlang-base                                     1:19.0-1                     amd64
ii  erlang-p1-tls                                   1.0.4-0.1~afa70              amd64
```

ejabberd is not fully installed as the service start fails during the installation.

**Comment by mathiasertl** [comment]
I use erlang 17 from backports, maybe that's the issue?

**Comment by tbeitter** [comment]
yes, a downgrade to 17.1 fixed the issue. I guess the issue is closed as you already said in the MUC that you will build a new package that's incompatible with erlang 19. Thanks for the help!

**Comment by mathiasertl** [comment]
I'm reopening this, because an incompatibility with Erlang 19 might not be my packages fault, but the package should still express this.

**Comment by beherit** [comment]
https://github.com/processone/ejabberd/issues/1176 ;)

**Comment by beherit** [comment]
It's strange - I have this same issue but I have Erlang 18 not 19... Maybe it's problem with erlang-p1-tls package?

**Comment by beherit** [comment]
In 16.08 problem still exists. Only downgrade to Erlang 17 works (I can't use Erlang 18 / 19).

**Comment by Gronkdalonka** [comment]
Same here, after erlang got updated to 18.x through debian backports ejabberd didn't start anymore. Downgrading erlang solved it.

**Comment by mathiasertl** [comment]
@Gronkdalonka so you're using the ejabberd package from debian backports?

**Comment by Gronkdalonka** [comment]
@mathiasertl nope, i am actually using ejabberd from the jabber.at repository

**Comment by beherit** [comment]
@mathiasertl any updates? For me ejabberd works only with erlang from Debian Jessie repo, when I try to install erlang from oficial site I have error.

**Comment by ZaphodB** [comment]
installing erlang-base 1:17.3-dfsg-4 from stable as opposed to 1:18.3.4.4+dfsg-1~bpo8+1 and downgrading all the relevant packages (aptitude) resolved the issue for me as well.
It was fine before 2016-09-08 01:07:48 upgrade ejabberd:amd64 16.06-2~bpo8+1 16.08-1~bpo8+1 .
