### ISSUE TITLE
invoke-rc.d: initscript ejabberd, action "start" failed.

### ISSUE THREAD

**Issue by protist** [jabber-at/ejabberd#13]
> What version of ejabberd are you using?

ejabberd 14.07-4+deb8u3

> What operating system (version) are you using?

Raspbian GNU/Linux 8

> How did you install ejabberd (source, package, distribution)?

Package (`sudo apt-get install ejabberd`)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Installation of dependencies worked, but post-installation script for `ejabberd` failed, preventing it from installing fully.
```
$ sudo apt-get install ejabberd
...
Creating config file /etc/ejabberd/ejabberd.yml with new version
Starting ejabberd...
invoke-rc.d: initscript ejabberd, action "start" failed.
dpkg: error processing package ejabberd (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of ejabberd-contrib:
 ejabberd-contrib depends on ejabberd (>= 14.07-1); however:
  Package ejabberd is not configured yet.

dpkg: error processing package ejabberd-contrib (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-18+deb8u6) ...
Processing triggers for menu (2.1.47) ...
Errors were encountered while processing:
 ejabberd
 ejabberd-contrib
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by protist** [comment]
Now I'm trying to remove the package, but I'm getting another error.
```
$ sudo apt-get purge ejabberd
...
Removing user `ejabberd' ...
Warning: group `ejabberd' has no more members.
userdel: user ejabberd is currently used by process 1996
/usr/sbin/deluser: `/usr/sbin/userdel ejabberd' returned error code 8. Exiting.
/usr/sbin/delgroup: `ejabberd' still has `ejabberd' as their primary group!
```
I killed the process (`epmd`), and now I could delete the user.

**Comment by mathiasertl** [comment]
Hi,

First, It seems like you use the stock `ejabberd-contrib` package from Debian. We have individual packages for each module, e.g. `ejabberd-mod-webpresence` etc., I will add a conflict to ejabberd-contrib in the next version.

The error happens because ejabberd fails to start during postinst. The  most likely issue is that you have older modules installed. `/var/log/ejabberd` should contain log files with more information.

**Comment by protist** [comment]
Thank you for the reply.

> First, It seems like you use the stock ejabberd-contrib package from Debian. We have individual packages for each module, e.g. ejabberd-mod-webpresence etc., I will add a conflict to ejabberd-contrib in the next version.

I'm not exactly sure what you mean by this. I had just tried to install `ejabberd`, and it pulled the `ejabberd-contrib` dependency automatically. I'm not sure what each of the packages you mention are.

> The error happens because ejabberd fails to start during postinst. The most likely issue is that you have older modules installed. /var/log/ejabberd should contain log files with more information.

This is the first time I've attempted to install ejabberd on this system, so I wouldn't have thought older modules would have been installed? Here is the first part of `/var/log/ejabberd/erl_crash_20161019-181740.dump`
```
=erl_crash_dump:0.3
Wed Oct 19 18:17:50 2016
Slogan: Problem starting the module mod_adhoc for host <<"localhost">> 
 options: []
 exit: {noproc,
           {gen_server,call,
               [ejabberd_iq_sup,
                {start_child,[<<"localhost">
System version: Erlang/OTP 17 [erts-6.2] [source] [smp:4:4] [async-threads:10] [kernel-poll:true]
Compiled: Mon Apr 13 10:38:35 2015
Taints: stringprep,p1_sha,p1_yaml
Atoms: 16655
```
And some lines from `/var/log/ejabberd/ejabberd.log`
```
2016-10-11 19:37:53.552 [error] <0.290.0>@ejabberd_listener:socket_error:560 Failed to open socket:
  {5222,ejabberd_c2s,[inet6,{ip,{0,0,0,0,0,0,0,0}}]}
Reason: address family not supported by protocol family
2016-10-11 19:37:53.553 [error] <0.290.0> CRASH REPORT Process ejabberd_listeners with 0 neighbours exited with reason: bad return value: {eafnosupport,{5222,{0,0,0,0,0,0,0,0},tcp}} in gen_server:init_it/6 line
 334
2016-10-11 19:37:53.554 [error] <0.233.0> Supervisor ejabberd_sup had child ejabberd_listener started with ejabberd_listener:start_link() at undefined exit with reason bad return value: {eafnosupport,{5222,{0,0
,0,0,0,0,0,0},tcp}} in context start_error
2016-10-11 19:37:53.637 [info] <0.38.0>@cyrsasl_digest:start:57 FQDN used to check DIGEST-MD5 SASL authentication: raspberrypi
2016-10-11 19:37:53.648 [critical] <0.38.0>@gen_mod:start_module:90 Problem starting the module mod_adhoc for host <<"localhost">> 
 options: []
 exit: {noproc,
           {gen_server,call,
               [ejabberd_iq_sup,
                {start_child,[<<"localhost">>,mod_adhoc,process_local_iq]},
                infinity]}}
[{gen_server,call,3,[{file,"gen_server.erl"},{line,190}]},
 {gen_iq_handler,add_iq_handler,6,[{file,"src/gen_iq_handler.erl"},{line,69}]},
 {mod_adhoc,start,2,[{file,"src/mod_adhoc.erl"},{line,48}]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,82}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,67}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,272}]}]
2016-10-11 19:37:53.649 [critical] <0.38.0>@gen_mod:start_module:95 ejabberd initialization was aborted because a module start failed.
```
There is also `error.log` and `crash.log` in this directory, both with references to ejabberd_listener. Please let me know if there is more information that I can provide.

**Comment by mathiasertl** [comment]
After talking with an ejabberd dev, this seems to be the key:

```
2016-10-11 19:37:53.552 [error] <0.290.0>@ejabberd_listener:socket_error:560 Failed to open socket:
  {5222,ejabberd_c2s,[inet6,{ip,{0,0,0,0,0,0,0,0}}]}
```

Can you double check your port 5222 config? You can paste the full YAML code for that directive here if you like. For comparison, we have our config [here](https://github.com/jabber-at/config/blob/master/ports.yml).

**Comment by mathiasertl** [comment]
also verify that you have a working IPv6 setup:

```
ping6 -c 1 ::1
```

**Comment by protist** [comment]
I didn't really understand specifically what you meant by port 5222, YAML, and your config. However, the problem was indeed IPv6 not being enabled.
```
$ ping6 -c 1 ::1
socket: Address family not supported by protocol
$ sudo modprobe ipv6
$ ping6 -c 1 ::1
PING ::1(::1) 56 data bytes
64 bytes from ::1: icmp_seq=1 ttl=64 time=0.116 ms

--- ::1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.116/0.116/0.116/0.000 ms
```
After enabling IPv6, ejabberrd installation worked fine. I'm not sure what you want to do with this issue, i.e. should the error message be more specific? If not, please feel free to close this issue. Thank you for your help.

**Comment by mathiasertl** [comment]
The configuration for ejabberd is in a YAML file, in `/etc/ejabberd/ejabberd.yml`. Port 5222 is the default port for XMPP, and this line:

```
2016-10-11 19:37:53.552 [error] <0.290.0>@ejabberd_listener:socket_error:560 Failed to open socket:
  {5222,ejabberd_c2s,[inet6,{ip,{0,0,0,0,0,0,0,0}}]}
```

indicates that ejabberd couldn't open port 5222 on the IPv6 interface.
