### ISSUE TITLE
Default language not work - @translate:load_dir:75 enoent

### ISSUE THREAD

**Issue by sdorpl** [jabber-at/ejabberd#14]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Debian 8 'Jessie' + updates

> How did you install ejabberd (source, package, distribution)?

from jabber.at repo

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hey!
I installed ejabberd 16.09 forum Jabber.at repo on Debian Jessie. I want to change the default language to Polish, but does not work. Other languages also do not work, the only English works. I getting an error @translate: load_dir 75 ENOENT in log files. Please help and sorry for my language, I use a translator

**Comment by mathiasertl** [comment]
(this was resolved in our MUC)
