### ISSUE TITLE
Problem with captcha

### ISSUE THREAD

**Issue by laptopdude90** [jabber-at/ejabberd#17]
> What version of ejabberd are you using?

16.01-2

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Package(apt-get install)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm trying to set up captcha. With it enabled, the server doesn't even start and crashes with the following message:

```
2017-04-19 21:28:13.778 [error] <0.341.0>@ejabberd_captcha:do_create_image:461 Failed to process output from "/usr/share/ejabberd/captcha.sh 202621". Maybe ImageMagick's Convert program is not installed.
2017-04-19 21:28:13.778 [critical] <0.341.0>@ejabberd_captcha:check_captcha_setup:614 Captcha is enabled in the option captcha_cmd, but it can't generate images.
2017-04-19 21:28:13.778 [error] <0.341.0> CRASH REPORT Process ejabberd_captcha with 0 neighbours exited with reason: bad return value: {error,captcha_cmd_enabled_but_fails} in gen_server:init_it/6 line 356
```

**Comment by mathiasertl** [comment]
16.01 is over a year old. It's not in our repos (neither is 17.01, in case you just made a typo) unless you're using a old, unsupported version of Ubuntu. Maybe you're using the stock version coming with Ubuntu?

In any case, `Maybe ImageMagick's Convert program is not installed.` says pretty clearly what's wrong.

**Comment by laptopdude90** [comment]
It is installed, and if I run convert I get a list of command line options. Furthermore, I can use the script and pipe the output into a png file and I get a valid captcha.

**Comment by mathiasertl** [comment]
This repo and issue tracker are for the packages we host in the APT repositories at jabber.at. See [here](https://jabber.at/p/apt-repository/) for more info. It seems you're using the stock version coming with Ubuntu, so this is simply the wrong issue tracker.

**Comment by laptopdude90** [comment]
I'm now getting this error:

Apr 20 08:26:56 XMPP-SERV sh[1202]: /usr/sbin/ejabberdctl: line 379: /proc/sys/kernel/random/uuid: Permission denied

**Comment by laptopdude90** [comment]
I also checked the permissions:

-r--r--r-- 1 root root 0 Apr 20 08:27 /proc/sys/kernel/random/uuid
