### ISSUE TITLE
Update from 1:17.01-2~ubuntu16.04 to 1:17.04-2~ubuntu16.04 fails Conflicts: erlang-p1-xmpp

### ISSUE THREAD

**Issue by github-tomster** [jabber-at/ejabberd#18]
> What version of ejabberd are you using?
1:17.01-2~ubuntu16.04

> What operating system (version) are you using?
Ubuntu Linux 16.04.1

> How did you install ejabberd (source, package, distribution)?
jabber.at package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

```
Updatable package information
Package name 	ejabberd
Update system 	APT
Package description 	distributed, fault-tolerant Jabber/XMPP server
Current state 		New version 17.04-2~ubuntu16.04
Installed version 	1:17.01-2~ubuntu16.04
Available version 	1:17.04-2~ubuntu16.04
```
```
The following packages have unmet dependencies:
 ejabberd : Conflicts: erlang-p1-xmpp (> 1.1.10) but 1.1.16-0.3~ubuntu16.04 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by mathiasertl** [comment]
Just pushed a new debian revision, everything should work now.

**Comment by github-tomster** [comment]
confirmed working on my setup. thank you.
