### ISSUE TITLE
KiND QUESTiON: where to find info about ejabberd 17.04-5

### ISSUE THREAD

**Issue by github-tomster** [jabber-at/ejabberd#21]
it is quite strange: my system shows an update for ejabberd ejabberd 17.04-4 to
ejabberd 17.04-5 but i am unable to find any changelog nor infos for that.
i am using the repository from jabber.at.
what is the right place to get the infos?
and pardon my blindness in advance.

**Comment by mathiasertl** [comment]
This place is... unless I manage to forget to push the new commit :-)

I just pushed and you see the changelog here: https://github.com/jabber-at/ejabberd/blob/master/debian/changelog
