### ISSUE TITLE
Ejabberd 18.x for Debian9 repository

### ISSUE THREAD

**Issue by danjde** [jabber-at/ejabberd#24]
Hi Developers,
Should be very useful to use repositories from where install Ejabberd 18.x.x version.
So as to keep the system updated directly via apt.

Thanks

Davide

**Comment by mathiasertl** [comment]
This is not the ejabberd development repository. It's for the Debian package we build for jabber.at

Nowadays you have even two options to use the newest ejabberd via apt, [our repositories](https://jabber.at/p/apt-repository/) or using the packages from Debian backports.

**Comment by danjde** [comment]
..hoops! :-D
Thanks for the useful information ;-)

Davide
