### ISSUE TITLE
Need new dependencies

### ISSUE THREAD

**Issue by beherit** [jabber-at/ejabberd#8]
Please take a look at https://github.com/processone/ejabberd/issues/760#issuecomment-144851446 Your package need new dependencies e.g. oauth2 package.

**Comment by mathiasertl** [comment]
I can confirm the missing dependencies. However ejabberd started for me without the missing libraries. Can you confirm that ejabberd starts fine if oauth is not configured?

If yes, I might make the oauth2 package an optional dependency if it requires additional libraries.

**Comment by beherit** [comment]
Yes, ejabberd starts fine but oauth doesn't work as well.

**Comment by mathiasertl** [comment]
The repositories now contain a package named `ejabberd-oauth2`. I do not have any working setup of that, so the package is untested. Does it work for you?

**Comment by beherit** [comment]
Yes, now I don't have any error.

**Comment by mathiasertl** [comment]
Ok great! that means I can close the issue ;-)

**Comment by cesarzagonel** [comment]
How can I install the missing package?

**Comment by mathiasertl** [comment]
This ticket has been closed for over a year. If you have any new problem, please file a new issue. And a good tip would be to provide a description of your problem, otherwise I won't be able to help you.
