### ISSUE TITLE
postinst script errors

### ISSUE THREAD

**Issue by JohnBrodie** [jabber-at/ejabberd#9]
It looks like there is garbage from a diff in the post install file at https://github.com/jabber-at/ejabberd/blob/master/debian/postinst#L52-L59.  This causes dpkg to throw an error on install.

**Comment by mathiasertl** [comment]
The script executes fine on my machine - it's also certainly not "garbage from a diff". Perhaps you'd like to be a bit more specific on the error dpkg throws during install?

**Comment by JohnBrodie** [comment]
My fault, I'm not overly familiar with some of the scripting being done here.  On a fresh Debian 8 machine, `apt-get install ejabberd` fails when using the jabber.at repo, with a message about the postinstall script.  If I try to run the script with bash, I get:

```
root@jabber1:/var/lib/dpkg/info# bash ejabberd.postinst configure
Can't exec "ejabberd.config": No such file or directory at /usr/share/perl/5.20/IPC/Open3.pm line 177.
open2: exec of ejabberd.config configure  failed at /usr/share/perl5/Debconf/ConfModule.pm line 59.
```

If I run it with /bin/sh it just quietly exits with a return code of 1.

I apologize for the false assumption - hadn't had my coffee yet.

**Comment by mathiasertl** [comment]
It is a /bin/sh script, and it's what ships with the upstream debian package. At the top of the script, there is a line `set -e`, can you add a line `set -x` after that and try executing it again? This should tell you the last command that's executed by /bin/sh.

**Comment by JohnBrodie** [comment]
Thanks for taking the time to look at this.

On a fresh VM running Debian 8.2 (Vagrant with the "debian/jessie64" box):

```
root@jabber3:/var/lib/dpkg/info# /bin/sh ejabberd.postinst
+ CONFIG_SOURCE=/usr/share/ejabberd/ejabberd.yml.example
+ CONFIG_TARGET=/etc/ejabberd/ejabberd.yml
+ mktemp
+ TEMPFILE=/tmp/tmp.OOqLqu2OBC
+ . /usr/share/debconf/confmodule
+ [ !  ]
+ PERL_DL_NONLAZY=1
+ export PERL_DL_NONLAZY
+ [  ]
+ exec /usr/share/debconf/frontend ejabberd.postinst
Can't exec "ejabberd.config": No such file or directory at /usr/share/perl/5.20/IPC/Open3.pm line 177.
open2: exec of ejabberd.config configure  failed at /usr/share/perl5/Debconf/ConfModule.pm line 59.
```

**Comment by mathiasertl** [comment]
I think dpkg will set some environment variables etc, try `apt-get install -f` instead, that will show you the real error...

**Comment by mathiasertl** [comment]
I must add: it works fine on a fresh pbuilder chroot. So there is definitely something strange going on here.

**Comment by JohnBrodie** [comment]
So there's a bunch of similar error messages in the logs after install (which with set -x appears to fail trying to start the ejabberd service).

```
2015-12-23 16:49:22.282 [error] <0.37.0> CRASH REPORT Process <0.37.0> with 0 neighbours exited with reason: bad return value {cannot_write_pid_file,"/run/ejabberd/ejabberd.pid",enoent} from ejabberd_app:start(normal, []) in application_master:init/4 line 133
2015-12-23 16:50:57.750 [error] <0.38.0>@ejabberd_app:write_pid_file:226 Cannot write PID file /run/ejabberd/ejabberd.pid
Reason: enoent
```
Due to `/var/run/ejabberd` not existing:

```
# stat /var/run/ejabberd
stat: cannot stat ‘/var/run/ejabberd’: No such file or directory
```

**Comment by mathiasertl** [comment]
I am somewhat at a loss why the directory wasn't created for you. systemd-tmpfiles should create the dir if you're using systemd, and the init script should create it if you don't.

In any case, could you try `ejabberdctl-create-run.patch` from the above commit, which should apply to `/usr/sbin/ejabberdctl`.
